### ISSUE TITLE
FEngine: Stagnant packet-indices received

### ISSUE THREAD

**Issue by radonnachie** [realtimeradio/vla-dev#16]
If I leave fengines streaming data to hashpipe, after n hours I return and see that hashpipe reports the current packet-index parsed is 1. Hashpipe still reports reception of packets, but the packet-index stays stagnant.

**Comment by jack-h** [comment]
This is definitely hashpipe and not the F-engines? If hashpipe is restarted (but the F-engines not touched) things start working again?

**Comment by radonnachie** [comment]
Touché
