### ISSUE TITLE
FEngine: reprogramming can kill the host

### ISSUE THREAD

**Issue by radonnachie** [realtimeradio/vla-dev#18]
I just saw this when reprogramming to tackle #16. But doing so hasn't killed the host before previously.

Attached is the TyanIPMI message related.
![image](https://user-images.githubusercontent.com/28019482/169482488-f92081e9-feff-41fd-a00f-9ed193bca517.png)
 
 So far haven't found a pattern to the occurence.

**Comment by radonnachie** [comment]
I think if we start unraveling issues in the packets themselves maybe we uncover something related. Not sure. 

Is the plan roughly that though, to see if other debugging uncovers this cause?

**Comment by radonnachie** [comment]
Accessing registers (there is a daemon that does) while programming (only consistent event that's a part of the phenomenon) could cause this, according to Jack.

Need to test if remoteobject (a hidden factor in this, that has been consistent) access really is sequential and not concurrent.

**Comment by jack-h** [comment]
Are you planning to investigate this now? If not I'll kill the daemon and see if that allows me to do the current thing I'm trying to do :)

**Comment by radonnachie** [comment]
Remote objects has been updated to sequentialise access to individual objects. All fpga servers have been updated to this version.

Let's see.
