### ISSUE TITLE
Lo `get_status` implementation

### ISSUE THREAD

**Issue by jack-h** [realtimeradio/vla-dev#23]
The `Lo` block should implement `get_status()` -- probably this should just return all the currently loaded LO shift frequencies, in friendly printable units

**Comment by jack-h** [comment]
To be annoying -- `get_status` is a method of the `Block` parent class, so should comply with the API of that (i.e., return a pair of dictionaries, one containing status key/vals, the other containing warning codes (of which probably there aren't any here, so the error dict would just be `{}`)

**Comment by jack-h** [comment]
https://github.com/realtimeradio/vla-dev/blob/d8afc10119d10ec0e4ef5374493814f11f6585b9/software/control_sw/src/blocks/block.py#L85

Eg. https://github.com/realtimeradio/vla-dev/blob/d8afc10119d10ec0e4ef5374493814f11f6585b9/software/control_sw/src/blocks/input.py#L167

**Comment by talonmyburgh** [comment]
Closed with this commit: b53d8de23df056f132c0f5ed21aa52e6bc690051
?
