### ISSUE TITLE
`set_lo_frequency_shift()` no good

### ISSUE THREAD

**Issue by radonnachie** [realtimeradio/vla-dev#27]
This is a core difference in the manual `configure_remotefpgas.py` and the automated `observe.py` processes: the former applies an LO F-Shift [as part of configuration](https://github.com/realtimeradio/vla-dev/blob/master/software/control_sw/src/cosmic_fengine.py#L634) while the later applies zero F-Shift at configuration, awaits certain criteria and then [directly sets the LO F-Shift](https://github.com/realtimeradio/vla-dev/blob/master/software/control_sw/src/cosmic_fengine.py#L841-L859).

Steps to reproduce
1. Manually configure with `configure_remotefpgas.py`
2. For each antenna configured use `set_lo_frequency_shift` to apply an LO F-Shift

Observation:
After step 1. the ingest GB/s is as expected. After step 2. the ingest GB/s falls (arbitrarily between the recipients) and hashpipe instance 0 crashes with `0x1 (local length error)` ([see](https://github.com/COSMIC-SETI/COSMIC-Commissioning/issues/14)).

**Comment by radonnachie** [comment]
At the very least we should disable_tx for the duration of the function.

**Comment by radonnachie** [comment]
This hasn't been an obvious issue in the case for <=2 antenna.
It's only really creeping up with more (currently 13 antenna).

**Comment by jack-h** [comment]
Does disabling TX successfully work around this?

**Comment by jack-h** [comment]
rev 13.6 of the firmware (inbound) will remove the need to sync the boards to load the LO phase accumulators. Instead, they can be commanded to load at a specific time (like the coarse delay block), and this has no effect on the higher level system.

**Comment by radonnachie** [comment]
I'll test this firmware now

**Comment by radonnachie** [comment]
https://github.com/realtimeradio/vla-dev/commit/5d9f0141aa1df6bb4cbc46aad4828bb542513b26

**Comment by talonmyburgh** [comment]
Issue is resolved with firmware version "adm_pcie_9h7_dts_dual_4x100g_dsp_8b_2022-10-09_2043.fpg" and the applying of `lo_fshifts` with `force_load()` in the [cosmic_f.cold_start()](https://github.com/realtimeradio/vla-dev/commit/1c51c7d2225e3614672157f5de70a4a9d32c4c6c). @jack-h is requested to review and close issue.
