### ISSUE TITLE
`is_synced` won't detect a missing lane

### ISSUE THREAD

**Issue by jack-h** [realtimeradio/vla-dev#42]
https://github.com/realtimeradio/vla-dev/blame/94b3a27f19d7cb88daf1da4f23cee6c02e398d52/software/control_sw/src/blocks/dts.py#L537

The sync test should be that the sync value snapshot is periodically all ones.
It is true that this means every entry should either be 0 or all ones, so other values indicate an error. But if the snapshot is zero everywhere that is also an error (and likely indicates a dead DTS lane)

**Comment by jack-h** [comment]
@talonmyburgh any chance I can just drop this on you

**Comment by talonmyburgh** [comment]
Patched with commit 5abe31a1450e0c7a788c225260d6ac5321a1d363
